(function(window){"use strict";
let currentUser=null,applicationId=null,editMode=false;
const fields={projectCode:"projectCode",projectSlug:"projectSlug",projectName:"projectName",businessName:"businessName",country:"country",state:"state",city:"city",industry:"industry",category:"category",businessRegistrationNumber:"businessRegistrationNumber",businessAddress:"businessAddress",contactEmail:"contactEmail",contactPhone:"contactPhone",website:"website",piWallet:"piWallet",fundingRequired:"fundingRequired",fundingAsset:"fundingAsset",investmentModel:"investmentModel",projectDurationDays:"projectDurationDays",projectDescription:"projectDescription"};
const el=id=>document.getElementById(id);
const value=k=>String((el(fields[k])&&el(fields[k]).value)||"").trim();
function setStatus(m,t){const s=el("formStatus");if(s){s.textContent=m||"";s.className="form-status"+(t?" "+t:"")}}
function deps(){if(!window.ALBukhrEnvironment||!window.ALBUKHR_SUPABASE||!window.AlbukhrPageAuthGuard)throw new Error("Required ALBUKHR core is unavailable.");if(!window.ALBukhrEnvironment.isKnown())throw new Error("ALBUKHR environment is not recognized.")}
function payload(){return{project_code:value("projectCode"),project_slug:value("projectSlug"),project_name:value("projectName"),business_name:value("businessName"),country:value("country"),contact_email:value("contactEmail"),project_description:value("projectDescription"),business_registration_number:value("businessRegistrationNumber")||null,industry:value("industry"),category:value("category"),state:value("state")||null,city:value("city")||null,business_address:value("businessAddress")||null,website:value("website")||null,contact_phone:value("contactPhone")||null,pi_wallet:value("piWallet")||null,funding_required:Number(value("fundingRequired")),funding_asset:value("fundingAsset"),investment_model:value("investmentModel"),project_duration_days:Number(value("projectDurationDays"))}}
function validate(p){["project_code","project_slug","project_name","business_name","country","contact_email","project_description","industry","category","funding_asset","investment_model"].forEach(k=>{if(!String(p[k]||"").trim())throw new Error("Please complete all required fields.")});if(!Number.isFinite(p.funding_required)||p.funding_required<=0)throw new Error("Funding Required must be greater than zero.");if(!Number.isInteger(p.project_duration_days)||p.project_duration_days<1)throw new Error("Project Duration must be at least 1 day.")}
function map(row){const m={projectCode:row.project_code,projectSlug:row.project_slug,projectName:row.project_name,businessName:row.business_name,country:row.country,state:row.state,city:row.city,industry:row.industry,category:row.category,businessRegistrationNumber:row.business_registration_number,businessAddress:row.business_address,contactEmail:row.contact_email,contactPhone:row.contact_phone,website:row.website,piWallet:row.pi_wallet,fundingRequired:row.funding_required,fundingAsset:row.funding_asset,investmentModel:row.investment_model,projectDurationDays:row.project_duration_days,projectDescription:row.project_description};Object.entries(m).forEach(([k,v])=>{if(v!=null&&el(k))el(k).value=v})}
async function loadEdit(){setStatus("Loading application for secure editing...");const network=window.ALBukhrEnvironment.getNetwork();const {data,error}=await window.ALBUKHR_SUPABASE.from("external_project_applications").select("*").eq("id",applicationId).eq("network",network).maybeSingle();if(error)throw error;if(!data)throw new Error("Application was not found or you do not have access to it.");const status=String(data.status||"draft").trim().toLowerCase();if(!["draft","revision_requested","revision","changes_requested"].includes(status))throw new Error("This application cannot be edited in its current status.");map(data);setStatus("Application loaded. Update the details and save your changes.","success")}
function assertSuccess(data,fallback){if(!data||typeof data!=="object"||data.success!==true)throw new Error((data&&data.message)||fallback)}
async function submit(e){e.preventDefault();const b=el("saveButton");try{const p=payload();validate(p);b.disabled=true;setStatus(editMode?"Saving secure application changes...":"Creating secure project application...");const r=editMode?await window.ALBUKHR_SUPABASE.rpc("update_external_project_application",{p_application_id:applicationId,p_payload:p}):await window.ALBUKHR_SUPABASE.rpc("create_external_project_application",p);if(r.error)throw r.error;assertSuccess(r.data,editMode?"Application update was not accepted.":"Application creation was not accepted.");setStatus(editMode?"Application updated successfully.":"Application created successfully.","success");b.textContent=editMode?"Saved":"Created";setTimeout(()=>location.replace("external-project-dashboard.html"),700)}catch(err){console.error("[ALBUKHR EXTERNAL CREATE]",err);setStatus("Unable to save application: "+(err.message||"Unknown error"),"error");b.disabled=false;b.textContent=editMode?"Save Changes":"Create Application"}}
function setup(){el("externalProjectForm").addEventListener("submit",submit);el("cancelButton").onclick=()=>location.href="external-project-dashboard.html";el("backButton").onclick=()=>location.href="external-project-dashboard.html";el("projectName").addEventListener("input",function(){if(editMode||value("projectSlug"))return;el("projectSlug").value=this.value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")})}
async function init(){try{deps();currentUser=await window.AlbukhrPageAuthGuard.waitForAuth();if(!currentUser)return;const n=window.ALBukhrEnvironment.getNetwork();el("networkIndicator").textContent=n.toUpperCase();el("authUsername").textContent=currentUser.username||"ALBUKHR User";el("authNetwork").textContent="Authenticated with Pi • "+n.toUpperCase();el("authAvatar").textContent=String(currentUser.username||"A").charAt(0).toUpperCase();applicationId=new URLSearchParams(location.search).get("application_id");editMode=Boolean(applicationId);if(editMode){el("modeEyebrow").textContent="EXTERNAL PROJECT APPLICATION";el("pageTitle").textContent="Edit External Project";el("pageDescription").textContent="Update your draft or revision-requested application within the ALBUKHR review framework.";el("saveButton").textContent="Save Changes"}setup();if(editMode)await loadEdit()}catch(err){console.error("[ALBUKHR EXTERNAL CREATE INIT]",err);setStatus("Application form unavailable: "+(err.message||"Unknown error"),"error");if(el("saveButton"))el("saveButton").disabled=true}}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init,{once:true}):init();
})(window);
