/* ALBUKHR External Project — draft-first. Mainnet writes use the trusted API only.
   Pi UID/network authority are never supplied by this browser to the Mainnet API.
   No localStorage is used; saved draft data remains server-side. */
(function(w,d){"use strict";
let user=null,id=null,status="draft",saving=false,queued=false,timer=null,lastSaved="",objectUrl=null;
const logo={url:null,path:null,width:null,height:null,format:null,size_bytes:null};
const $=x=>d.getElementById(x),UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function msg(s,t){let e=$("formStatus");if(e){e.textContent=s;e.className="form-status"+(t?" "+t:"")}}
function draftMsg(s){if($("draftSaveStatus"))$("draftSaveStatus").textContent=s}
function logoMsg(s,t){let e=$("externalCreateLogoStatus");if(e){e.textContent=s;e.className="form-status"+(t?" "+t:"")}}
function net(){if(!w.ALBukhrEnvironment||!w.ALBukhrEnvironment.isKnown())throw Error("ALBUKHR environment is unavailable or unrecognized.");let n=String(w.ALBukhrEnvironment.getNetwork()||"").toLowerCase();if(!["mainnet","testnet"].includes(n))throw Error("Invalid ALBUKHR network.");return n}
function deps(){if(!w.ALBUKHR_SUPABASE||!w.AlbukhrPageAuthGuard||!w.ALBukhrExternalProjectApi)throw Error("Required ALBUKHR security components are unavailable.");net()}
function uid(){let v=w.AlbukhrPageAuthGuard?.getPiUid?.()||user?.pi_uid||user?.uid;if(!v)throw Error("Authenticated Pi UID is unavailable.");return String(v).trim()}
function val(k){return $(k)?String($(k).value||"").trim():""}
function token(n=8){let s="";try{const a=new Uint8Array(n);w.crypto.getRandomValues(a);for(const x of a)s+=x.toString(16).padStart(2,"0")}catch(_){s=Math.random().toString(16).slice(2).padEnd(n*2,"0")}return s.slice(0,n*2).toUpperCase()}
function ensureIdentifiers(){const name=val("projectName");if(!name)return;const code=$("projectCode");if(code&&!val("projectCode"))code.value="EXT-"+token(4);const slugField=$("projectSlug");if(slugField&&!val("projectSlug")){const clean=slug(name);slugField.value=clean||("project-"+token(4).toLowerCase())}}
function hasBaseline(){return !!(val("projectName")&&val("businessName")&&val("country")&&val("contactEmail"))}
function slug(v){return String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
function editable(v){return ["draft","needs_revision"].includes(String(v||"").toLowerCase().replace(/\s+/g,"_"))}
function data(){ensureIdentifiers();let name=val("projectName");return {
p_project_name:name,p_business_name:val("businessName")||null,p_country:val("country")||null,p_contact_email:val("contactEmail")||null,
p_project_code:val("projectCode")||null,p_project_slug:slug(val("projectSlug")||name)||null,p_project_description:val("projectDescription")||null,
p_business_registration_number:val("businessRegistrationNumber")||null,p_industry:val("industry")||null,p_category:val("category")||null,
p_state:val("state")||null,p_city:val("city")||null,p_business_address:val("businessAddress")||null,p_website:val("website")||null,
p_contact_phone:val("contactPhone")||null,p_pi_wallet:val("piWallet")||null,
p_funding_required:val("fundingRequired")?Number(val("fundingRequired")):null,p_funding_asset:val("fundingAsset")||"PI",
p_investment_model:val("investmentModel")||null,p_project_duration_days:val("projectDurationDays")?Number(val("projectDurationDays")):null}}
function validate(x,full){
if(!x.p_project_name)throw Error("Enter the Project Name to create or save the draft.");
if(x.p_project_name.length>200)throw Error("Project Name must be 200 characters or fewer.");
if(!x.p_business_name)throw Error("Business Name is required to create the draft. You can edit it later.");
if(!x.p_country)throw Error("Country is required to create the draft. You can edit it later.");
if(!x.p_contact_email)throw Error("Contact Email is required to create the draft. You can edit it later.");
if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x.p_contact_email))throw Error("Enter a valid Contact Email.");
if(!x.p_project_code||!/^[A-Za-z0-9][A-Za-z0-9_-]{1,63}$/.test(x.p_project_code))throw Error("A valid Project Code could not be generated. Enter one manually.");
if(!x.p_project_slug||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(x.p_project_slug))throw Error("Project Slug must use lowercase letters, numbers and single hyphens only.");
if(x.p_funding_required!==null&&(!Number.isFinite(x.p_funding_required)||x.p_funding_required<=0))throw Error("Funding must be greater than zero or left blank.");
if(x.p_project_duration_days!==null&&(!Number.isInteger(x.p_project_duration_days)||x.p_project_duration_days<1||x.p_project_duration_days>36500))throw Error("Duration must be 1–36,500 days or left blank.");
if(x.p_website){try{let u=new URL(x.p_website);if(!["http:","https:"].includes(u.protocol))throw 0}catch(_){throw Error("Website must use a valid http:// or https:// URL.")}}
if(full){for(let [k,n] of [["p_industry","Industry"],["p_category","Category"],["p_project_description","Project Description"],["p_investment_model","Investment Model"],["p_funding_required","Funding Required"],["p_project_duration_days","Project Duration"]])if(x[k]===null||x[k]==="")throw Error(n+" is required before continuing.")}return x}
function fp(x){return JSON.stringify(x)}
function params(x){return Object.assign({p_application_id:id,p_pi_uid:uid(),p_network:net()},x||{})}
async function rpc(n,a){let r=await w.ALBUKHR_SUPABASE.rpc(n,a);if(r.error)throw r.error;return r.data}
async function create(x){let r=net()==="mainnet"?await w.ALBukhrExternalProjectApi.createApplication(x):await rpc("create_my_external_project_application",Object.assign({p_pi_uid:uid(),p_network:net()},x));
let c=r&&typeof r==="object"?(r.application_id||r.id||r.data?.application_id||r.data?.id||r.data||""):r;let v=String(c||"").trim();if(!UUID.test(v))throw Error("Server did not confirm a valid draft ID.");return v}
async function update(x){let r=net()==="mainnet"?await w.ALBukhrExternalProjectApi.updateApplication(id,x):await rpc("update_my_external_project_application",params(x));if(r!==true)throw Error("Server did not confirm the draft update.")}
function markSaved(){let t=$("pageTitle"),e=$("modeEyebrow");if(t)t.textContent="Edit External Project Draft";if(e)e.textContent="EXTERNAL PROJECT APPLICATION";history.replaceState({applicationId:id},"","external-create.html?application_id="+encodeURIComponent(id));draftMsg("Draft saved securely. You can leave and return to edit or complete the remaining fields.")}
async function saveNow(quiet){if(saving){queued=true;return false}saving=true;try{let x=validate(data(),false);if(!id){draftMsg("Creating draft securely...");id=await create(x);markSaved();lastSaved=fp(x)}else{let f=fp(x);if(f!==lastSaved){await update(x);lastSaved=f}markSaved()}if(!quiet)msg("Draft saved. Continue filling the form whenever you are ready.","success");return true}catch(e){draftMsg("Draft was not saved. Complete the required fields or retry after correcting the error.");if(!quiet)msg("Unable to save draft: "+(e.message||"Unknown error"),"error");console.error("[ALBUKHR EXTERNAL CREATE] save failed",e);return false}finally{saving=false;if(queued){queued=false;schedule(200)}}}
function schedule(ms=900){clearTimeout(timer);if(!val("projectName")){draftMsg("Complete Project Name, Business Name, Country and Contact Email to create a draft.");return}if(!hasBaseline()){draftMsg("Draft not created yet. Complete the four required fields: Project Name, Business Name, Country and Contact Email.");return}timer=setTimeout(async()=>{if(saving){queued=true;return}if(await saveNow(true))draftMsg("All current changes are saved securely.")},ms)}
function setLogo(row){row=row||{};Object.assign(logo,{url:row.logo_url||null,path:row.logo_path||null,width:row.logo_width??null,height:row.logo_height??null,format:row.logo_format||null,size_bytes:row.logo_size_bytes??null});renderLogo()}
function logoReady(){return !!(logo.url&&logo.path&&Number(logo.width)>=400&&Number(logo.height)>=400&&["png","jpg","jpeg"].includes(String(logo.format||"").toLowerCase())&&Number(logo.size_bytes)>0&&Number(logo.size_bytes)<=1048576)}
function renderLogo(){let img=$("externalCreateLogoImage"),empty=$("externalCreateLogoEmpty");if(img&&logo.url){img.src=logo.url+(logo.url.includes("?")?"&":"?")+"v="+Date.now();img.hidden=false}else if(img&&!$("externalCreateLogoFile")?.files?.length){img.removeAttribute("src");img.hidden=true}if(empty)empty.hidden=!!(logo.url||$("externalCreateLogoFile")?.files?.length);if(net()==="testnet"){logoMsg("Secure logo upload is available on Mainnet only.","info");return}logoMsg(logoReady()?"Logo registered: "+logo.width+" × "+logo.height+" px • "+String(logo.format).toUpperCase()+".":"Save the draft first, then save the logo.","info")}
function mime(f){let t=String(f?.type||"").toLowerCase(),n=String(f?.name||"").toLowerCase();if(t==="image/png"||t==="image/jpeg")return t;if(n.endsWith(".png"))return"image/png";if(n.endsWith(".jpg")||n.endsWith(".jpeg"))return"image/jpeg";return""}
async function inspect(f){if(!f)throw Error("Select a project logo first.");if(f.size<1||f.size>1048576)throw Error("Logo must be greater than 0 bytes and no larger than 1 MB.");let m=mime(f);if(!m)throw Error("Logo must be PNG or JPG/JPEG.");let b=null,u=null,wid=0,hei=0;try{if(w.createImageBitmap)try{b=await w.createImageBitmap(f);wid=b.width;hei=b.height}catch(_){}if(!wid||!hei){u=URL.createObjectURL(f);let im=new Image();await new Promise((ok,no)=>{im.onload=ok;im.onerror=()=>no(Error("Browser could not read this image; select the original PNG/JPEG."));im.src=u});wid=im.naturalWidth||im.width;hei=im.naturalHeight||im.height}if(wid<400||hei<400)throw Error("Logo must be at least 400 × 400 pixels.");return{mime:m,width:wid,height:hei}}finally{if(b?.close)b.close();if(u)URL.revokeObjectURL(u)}}
async function load(){let r=net()==="mainnet"?await w.ALBukhrExternalProjectApi.getApplication(id):await rpc("get_my_external_project_detail",params());let row=Array.isArray(r)?r[0]:r;if(!row)throw Error("Application not found or access denied.");status=String(row.status||"draft").toLowerCase();if(!editable(status))throw Error("This application cannot be edited in its current status.");let fields={projectName:"project_name",businessName:"business_name",projectCode:"project_code",projectSlug:"project_slug",country:"country",state:"state",city:"city",industry:"industry",category:"category",businessRegistrationNumber:"business_registration_number",businessAddress:"business_address",contactEmail:"contact_email",contactPhone:"contact_phone",website:"website",piWallet:"pi_wallet",fundingRequired:"funding_required",fundingAsset:"funding_asset",investmentModel:"investment_model",projectDurationDays:"project_duration_days",projectDescription:"project_description"};for(let [el,key] of Object.entries(fields))if($(el)&&row[key]!=null)$(el).value=row[key];setLogo(row);if(net()==="mainnet")try{let z=await w.ALBukhrExternalProjectApi.getLogo(id);setLogo(Array.isArray(z)?z[0]:z)}catch(e){console.warn("Logo lookup failed",e)}lastSaved=fp(data());markSaved();msg("Draft loaded. Your saved information has been restored.","success")}
async function saveLogo(){if(saving)return;let f=$("externalCreateLogoFile")?.files?.[0];try{if(net()!=="mainnet")throw Error("Secure logo upload is available on Mainnet only.");let meta=await inspect(f);if(!id){if(!hasBaseline())throw Error("To create the draft and attach a logo, complete Project Name, Business Name, Country and Contact Email first.");if(!await saveNow(true)||!id)throw Error("Save the draft before uploading the logo.")}else if(!await saveNow(true))throw Error("Save draft changes before uploading the logo.");saving=true;let b=$("saveProjectLogoButton");if(b){b.disabled=true;b.textContent="Uploading Logo..."}logoMsg("Uploading and registering logo securely...","info");let r=await w.ALBukhrExternalProjectApi.uploadLogo(id,f);setLogo(r||{});if(!logoReady())throw Error("Server did not confirm logo registration.");msg("Logo saved. Your draft remains available.","success")}catch(e){logoMsg(e.message||"Logo upload failed.","error");msg("Unable to save logo: "+(e.message||"Unknown error"),"error")}finally{saving=false;let b=$("saveProjectLogoButton");if(b){b.disabled=false;b.textContent="Save Logo"}if(queued){queued=false;schedule(200)}}}
function bind(){ $("externalProjectForm").addEventListener("submit",e=>{e.preventDefault();saveNow(false)});
$("saveProjectLogoButton").addEventListener("click",saveLogo);$("cancelButton").addEventListener("click",()=>location.assign("external-project-dashboard.html"));
$("continueApplicationButton").addEventListener("click",async()=>{try{if(!hasBaseline())throw Error("Complete Project Name, Business Name, Country and Contact Email to create the draft first.");if(!await saveNow(false))return;location.assign("external-project-detail.html?application_id="+encodeURIComponent(id))}catch(e){msg(e.message||"Unable to open the draft.","error")}});
$("projectName").addEventListener("input",()=>{let s=$("projectSlug");if(s&&!s.dataset.userEdited)s.value=slug(val("projectName"));schedule(800)});
$("projectSlug").addEventListener("input",()=>{$("projectSlug").dataset.userEdited="true";schedule()});
for(let e of d.querySelectorAll("#externalProjectForm input:not(#externalCreateLogoFile),#externalProjectForm textarea"))if(!["projectName","projectSlug"].includes(e.id)){e.addEventListener("input",()=>schedule());e.addEventListener("change",()=>schedule(250))}
$("externalCreateLogoFile").addEventListener("change",async()=>{let f=$("externalCreateLogoFile").files[0];if(!f){renderLogo();return}if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(f);$("externalCreateLogoImage").src=objectUrl;$("externalCreateLogoImage").hidden=false;$("externalCreateLogoEmpty").hidden=true;try{let m=await inspect(f);logoMsg("Selected logo: "+m.width+" × "+m.height+" px • "+m.mime.toUpperCase().replace("IMAGE/","")+". Ready to save.","success")}catch(e){logoMsg(e.message,"error")}})}
async function init(){try{deps();user=await w.AlbukhrPageAuthGuard.waitForAuth();if(!user)return;bind();let n=net(),name=user.username||user.pi_username||"ALBUKHR User";$("networkIndicator").textContent=n.toUpperCase();$("authUsername").textContent=name;$("authNetwork").textContent="Authenticated with Pi • "+n.toUpperCase();$("authAvatar").textContent=name.charAt(0).toUpperCase();if(n==="testnet")document.querySelector(".external-logo-section").hidden=true;id=new URLSearchParams(location.search).get("application_id");if(id&&!UUID.test(id))throw Error("Application ID is invalid.");if(id)await load();else{renderLogo();msg("Complete Project Name, Business Name, Country and Contact Email to create a secure draft. Other details can be added or edited later.");draftMsg("No draft saved yet. Complete the four required fields to create it.")}}catch(e){console.error("[ALBUKHR EXTERNAL CREATE] init failed",e);msg("Application form unavailable: "+(e.message||"Unknown error"),"error");for(let k of ["saveDraftButton","saveProjectLogoButton","continueApplicationButton"])if($(k))$(k).disabled=true}}
if(d.readyState==="loading")d.addEventListener("DOMContentLoaded",init,{once:true});else init();
})(window,document);
