/* ALBUKHR EXTERNAL PROJECT CREATE / EDIT
 * Mainnet uses the trusted External Project API adapter.
 * Testnet retains the existing applicant RPC contract until a trusted
 * Testnet External Project gateway/schema is provisioned.
 */
(function(window,document){
"use strict";
let user=null,id=null,status="draft",edit=false,saving=false;
const $=id=>document.getElementById(id);
function setStatus(m,t){const e=$("formStatus");if(e){e.textContent=String(m||"");e.className="form-status"+(t?" "+t:"");}}
function deps(){if(!window.ALBukhrEnvironment)throw new Error("ALBUKHR Environment Core is unavailable.");if(!window.ALBUKHR_SUPABASE)throw new Error("ALBUKHR Supabase Core is unavailable.");if(!window.AlbukhrPageAuthGuard)throw new Error("ALBUKHR Page Auth Guard is unavailable.");if(!window.ALBukhrExternalProjectApi)throw new Error("ALBUKHR External Project API is unavailable.");if(!window.ALBukhrEnvironment.isKnown())throw new Error("ALBUKHR environment is not recognized.");}
function net(){const n=String(window.ALBukhrEnvironment.getNetwork()||"").trim().toLowerCase();if(!["mainnet","testnet"].includes(n))throw new Error("Invalid ALBUKHR network.");return n;}
function uid(){const v=window.AlbukhrPageAuthGuard?.getPiUid?.()||user?.pi_uid||user?.uid;if(!v)throw new Error("Authenticated Pi UID is unavailable.");return String(v).trim();}
function val(k){const e=$(k);return e?String(e.value||"").trim():"";}
function norm(v){return String(v||"draft").trim().toLowerCase().replace(/\s+/g,"_");}
function editable(v){return["draft","needs_revision"].includes(norm(v));}
function payload(){return{p_project_name:val("projectName"),p_business_name:val("businessName"),p_country:val("country"),p_contact_email:val("contactEmail"),p_project_code:val("projectCode")||null,p_project_slug:val("projectSlug")||null,p_project_description:val("projectDescription")||null,p_business_registration_number:val("businessRegistrationNumber")||null,p_industry:val("industry")||null,p_category:val("category")||null,p_state:val("state")||null,p_city:val("city")||null,p_business_address:val("businessAddress")||null,p_website:val("website")||null,p_contact_phone:val("contactPhone")||null,p_pi_wallet:val("piWallet")||null,p_funding_required:val("fundingRequired")?Number(val("fundingRequired")):null,p_funding_asset:val("fundingAsset")||"PI",p_investment_model:val("investmentModel")||null,p_project_duration_days:val("projectDurationDays")?Number(val("projectDurationDays")):null};}
function validate(p){for(const k of["p_project_name","p_business_name","p_country","p_contact_email"])if(!String(p[k]||"").trim())throw new Error("Please complete all required fields.");if((p.p_project_description||"").length>10000)throw new Error("Project description is too long.");if(p.p_funding_required!==null&&(!Number.isFinite(p.p_funding_required)||p.p_funding_required<=0))throw new Error("Funding Required must be greater than zero.");if(p.p_project_duration_days!==null&&(!Number.isInteger(p.p_project_duration_days)||p.p_project_duration_days<1))throw new Error("Project Duration must be at least 1 day.");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.p_contact_email))throw new Error("Please provide a valid contact email.");}
function map(row){const m={projectCode:row.project_code,projectSlug:row.project_slug,projectName:row.project_name,businessName:row.business_name,country:row.country,state:row.state,city:row.city,industry:row.industry,category:row.category,businessRegistrationNumber:row.business_registration_number,businessAddress:row.business_address,contactEmail:row.contact_email,contactPhone:row.contact_phone,website:row.website,piWallet:row.pi_wallet,fundingRequired:row.funding_required,fundingAsset:row.funding_asset,investmentModel:row.investment_model,projectDurationDays:row.project_duration_days,projectDescription:row.project_description};Object.entries(m).forEach(([k,v])=>{if($(k)&&v!==null&&v!==undefined)$(k).value=v;});}
async function rpc(name,p){const r=await window.ALBUKHR_SUPABASE.rpc(name,p);if(r.error)throw r.error;return r.data;}
function params(extra){return Object.assign({p_application_id:id,p_pi_uid:uid(),p_network:net()},extra||{});}
async function load(){setStatus("Loading your external project application...");const data=net()==="mainnet"?await window.ALBukhrExternalProjectApi.getApplication(id):await rpc("get_my_external_project_detail",params());const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error("Application was not found or access was denied.");status=norm(row.status);if(!editable(status))throw new Error("This application cannot be edited in its current status.");map(row);setStatus(status==="needs_revision"?"ALBUKHR requested changes. Update the application, then continue from the detail page.":"Application loaded successfully. You can continue editing.","success");}
async function create(p){return net()==="mainnet"?String(await window.ALBukhrExternalProjectApi.createApplication(p)):String(await rpc("create_my_external_project_application",Object.assign({p_pi_uid:uid(),p_network:net()},p)));}
async function update(p){const r=net()==="mainnet"?await window.ALBukhrExternalProjectApi.updateApplication(id,p):await rpc("update_my_external_project_application",Object.assign({p_application_id:id,p_pi_uid:uid(),p_network:net()},p));if(r!==true)throw new Error("Application update was not accepted.");}
function ui(){$("externalProjectForm")?.addEventListener("submit",save);$("cancelButton")?.addEventListener("click",()=>location.assign("external-project-dashboard.html"));const n=$("projectName"),s=$("projectSlug");n?.addEventListener("input",()=>{if(s&&!s.value.trim())s.value=String(n.value||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");});}
function auth(){const n=net(),u=user?.username||user?.pi_username||"ALBUKHR User";if($("networkIndicator"))$("networkIndicator").textContent=n.toUpperCase();if($("authUsername"))$("authUsername").textContent=u;if($("authNetwork"))$("authNetwork").textContent="Authenticated with Pi • "+n.toUpperCase();if($("authAvatar"))$("authAvatar").textContent=u.charAt(0).toUpperCase();if(edit){if($("modeEyebrow"))$("modeEyebrow").textContent="EXTERNAL PROJECT APPLICATION";if($("pageTitle"))$("pageTitle").textContent="Edit External Project";}}
async function save(e){e.preventDefault();if(saving)return;saving=true;const b=$("saveDraftButton");try{const p=payload();validate(p);if(b){b.disabled=true;b.textContent=edit?"Saving...":"Creating...";}if(edit){await update(p);setStatus("Application changes saved successfully.","success");}else{id=await create(p);edit=true;status="draft";location.replace("external-project-detail.html?application_id="+encodeURIComponent(id));return;}}catch(err){console.error(err);setStatus("Unable to save application: "+(err?.message||"Unknown error"),"error");}finally{saving=false;if(b){b.disabled=false;b.textContent=edit?"Save Changes":"Create Application";}}}
async function init(){try{deps();user=await window.AlbukhrPageAuthGuard.waitForAuth();if(!user)return;id=new URLSearchParams(location.search).get("application_id");edit=!!id;ui();auth();if(edit)await load();else setStatus("Complete the project information and create your application.");}catch(e){console.error("[ALBUKHR EXTERNAL CREATE]",e);setStatus("Application form unavailable: "+(e?.message||"Unknown error"),"error");if($("saveDraftButton"))$("saveDraftButton").disabled=true;}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})(window,document);
